name: Auto

on:
  schedule:
    - cron: "11 0 * * *"
    - cron: "48 0 * * *"
    - cron: "12 1 * * *"
    - cron: "49 1 * * *"
    - cron: "13 2 * * *"
    - cron: "50 2 * * *"
    - cron: "14 3 * * *"
    - cron: "37 3 * * *"
    - cron: "15 4 * * *"
    - cron: "38 4 * * *"
    - cron: "16 5 * * *"
    - cron: "49 5 * * *"
    - cron: "19 6 * * *"
    - cron: "51 6 * * *"
    - cron: "21 7 * * *"
    - cron: "52 7 * * *"
    - cron: "07 8 * * *"
    - cron: "36 8 * * *"
    - cron: "08 9 * * *"
    - cron: "41 9 * * *"
    - cron: "11 10 * * *"
    - cron: "44 10 * * *"
    - cron: "12 11 * * *"
    - cron: "45 11 * * *"
    - cron: "12 12 * * *"
    - cron: "43 12 * * *"
    - cron: "13 13 * * *"
    - cron: "43 13 * * *"
    - cron: "13 14 * * *"
    - cron: "43 14 * * *"
    - cron: "13 15 * * *"
    - cron: "44 15 * * *"
    - cron: "14 16 * * *"
    - cron: "44 16 * * *"
    - cron: "11 17 * * *"
    - cron: "44 17 * * *"
    - cron: "12 18 * * *"
    - cron: "46 18 * * *"
    - cron: "13 19 * * *"
    - cron: "46 19 * * *"
    - cron: "11 20 * * *"
    - cron: "46 20 * * *"
    - cron: "12 21 * * *"
    - cron: "44 21 * * *"
    - cron: "14 22 * * *"
    - cron: "47 22 * * *"
    - cron: "13 23 * * *"
    - cron: "46 23 * * *"
  workflow_dispatch:

env:
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
  DIFY_INPUTS: ${{ secrets.DIFY_INPUTS }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
  AIBOTK_KEY: ${{ secrets.AIBOTK_KEY }}
  AIBOTK_ROOM_RECIVER: ${{ secrets.AIBOTK_ROOM_RECIVER }}
  AIBOTK_CONTACT_RECIVER: ${{ secrets.AIBOTK_CONTACT_RECIVER }}

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          yarn
          yarn workflowDify
