name: Auto

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "30 0 * * *"
    - cron: "0 1 * * *"
    - cron: "30 1 * * *"
    - cron: "0 2 * * *"
    - cron: "30 2 * * *"
    - cron: "0 3 * * *"
    - cron: "30 3 * * *"
    - cron: "0 4 * * *"
    - cron: "30 4 * * *"
    - cron: "0 5 * * *"
    - cron: "30 5 * * *"
    - cron: "0 6 * * *"
    - cron: "30 6 * * *"
    - cron: "0 7 * * *"
    - cron: "30 7 * * *"
    - cron: "0 8 * * *"
    - cron: "30 8 * * *"
    - cron: "0 9 * * *"
    - cron: "30 9 * * *"
    - cron: "0 10 * * *"
    - cron: "30 10 * * *"
    - cron: "0 11 * * *"
    - cron: "30 11 * * *"
    - cron: "0 12 * * *"
    - cron: "30 12 * * *"
    - cron: "0 13 * * *"
    - cron: "30 13 * * *"
    - cron: "0 14 * * *"
    - cron: "30 14 * * *"
    - cron: "0 15 * * *"
    - cron: "30 15 * * *"
    - cron: "0 16 * * *"
    - cron: "30 16 * * *"
    - cron: "0 17 * * *"
    - cron: "30 17 * * *"
    - cron: "0 18 * * *"
    - cron: "30 18 * * *"
    - cron: "0 19 * * *"
    - cron: "30 19 * * *"
    - cron: "0 20 * * *"
    - cron: "30 20 * * *"
    - cron: "0 21 * * *"
    - cron: "30 21 * * *"
    - cron: "0 22 * * *"
    - cron: "30 22 * * *"
    - cron: "0 23 * * *"
    - cron: "30 23 * * *"
  workflow_dispatch:

env:
  DIFY_TOKENS: ${{ secrets.DIFY_TOKENS }}
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
  DIFY_INPUTS: ${{ secrets.DIFY_INPUTS }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
  AIBOTK_KEY: ${{ secrets.AIBOTK_KEY }}
  AIBOTK_ROOM_RECIVER: ${{ secrets.AIBOTK_ROOM_RECIVER }}
  AIBOTK_CONTACT_RECIVER: ${{ secrets.AIBOTK_CONTACT_RECIVER }}

jobs:
  DifyWorkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          yarn
          yarn workflowDify
